### ISSUE TITLE
IMPROVE - Unit test status badge in Readme

### ISSUE THREAD

**Issue by anupdsouza** [mikaelacaron/Basic-Car-Maintenance#241] opened 2023-10-29 07:40 UTC
## Describe the feature you want to improve
Add a unit test status badge in the readme to provide a quick glance of the unit test workflow status.

As discussed in https://github.com/mikaelacaron/Basic-Car-Maintenance/pull/194, I'd like to add a unit test status badge to the readme.

**Comment by anupdsouza** [comment] 2023-10-29 07:41
Hey @mikaelacaron, this is a quick one that I discussed in my PR #194. Could you assign it to me pls?

**Comment by anupdsouza** [comment] 2023-10-29 07:55
I just noticed that you created an issue #235 for this marked as first timers only. Please feel free to close this issue if you feel so. I've left the associated PR open for now, I can close it in case u decide to close this issue.

**Comment by mikaelacaron** [comment] 2023-10-29 16:57
I will be closing this issue because it's a duplicate of #235  , and also yes I'll be closing your PR as well

**Closed as completed by mikaelacaron** 2023-10-29 16:57 UTC
Labels: improvement
